Feature/mail
sliit-foss/rsvp pull request #27
Opened 2021-02-28 10:08 UTC by susithrupasinghe

## Purpose

Sending Mails to user/ set of users #6
## Goals

1. Sending emails
2. Checking availability of SMTP

## Approach

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have performed a self-review of my own code
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

2021-02-28 14:30 UTC, ebonynon reviewed
There is some code formatting issues. Remove unnecessary line gaps and try [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#:~:text=Prettier%20Formatter%20for%20Visual%20Studio%20Code%20Prettier%20is,%C2%B7%20TypeScript%20%C2%B7%20Flow%20%C2%B7%20JSX%20%C2%B7%20JSON)

2021-02-28 14:30 UTC, ebonynon commented on src/api/mails/mail.constants.js
> +
Remove empty two lines

2021-02-28 14:30 UTC, ebonynon commented on src/api/mails/mail.controller.js
> +
Remove unnecessary empty lines on code blocks

2021-02-28 14:30 UTC, ebonynon commented on src/api/routes.js
> +router.use('/api/v1/mail', mailRouter);
My bad bn, can you change as `/mail`

2021-02-28 15:25 UTC, susithrupasinghe commented on src/api/routes.js
> +router.use('/api/v1/mail', mailRouter);
Fixed

2021-02-28 15:25 UTC, susithrupasinghe commented on src/api/mails/mail.controller.js
> +
Fixed

2021-02-28 15:25 UTC, susithrupasinghe commented on src/api/mails/mail.constants.js
> +
fixed

2021-03-01 03:20 UTC, Shehanka commented on src/api/mails/mail.constants.js
> +};
Don't push secrets to public repository. Gitignore it. when we're deploying the app we can put this as a config file. But still wondering how we configure this for github actions 🤨. Need to find a way

2021-03-01 03:22 UTC, Shehanka requested changes
PR is overall good. But need to find a way for that. 

@ebonynon @susithrupasinghe Let's discuss about that in discussion

2021-03-01 03:31 UTC, Shehanka approved these changes

2021-03-01 03:32 UTC, Shehanka commented
Gonna merge this for now. Let's discuss the issue in here https://github.com/sliit-foss/rsvp/discussions/29

2021-03-01 03:33 UTC, merged