WIP: Attendees endpoint init
sliit-foss/rsvp pull request #31
Opened 2021-03-04 08:19 UTC by LayanJay

## Purpose

The purpose of this PR is to fix #<issue-number>

## Goals

## Approach

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have performed a self-review of my own code
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Related PRs
 

## Learning

2021-03-04 08:21 UTC, Shehanka commented
@LayanJay can u resolve the conflict

2021-03-04 08:23 UTC, Shehanka requested changes

2021-03-04 08:23 UTC, Shehanka commented on npm-debug.log
> +19 verbose headers    [ '__cfduid=dc3d9cdc625570a40445439c01e04364d1614529800; expires=Tue, 30-Mar-21 16:30:00 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
gitignore log file

2021-03-04 14:16 UTC, ebonynon reviewed
Set info and error logs. Please remove yarn.lock

2021-03-04 14:16 UTC, ebonynon commented on .gitignore
> +
Add yarn.lock file

2021-03-04 14:16 UTC, ebonynon commented on src/api/attendees/attendee.controller.js
> +    const attendee = await AttendeeService.createAttendee(req.body);
Set logs `logger.info(....)`

2021-03-04 14:16 UTC, ebonynon commented on src/api/attendees/attendee.controller.js
> +      .status(HTTP_STATUS.INTERNAL_SERVER_ERROR)
Set error logs `logger.error(....)`

2021-03-04 14:16 UTC, ebonynon commented on src/api/attendees/attendee.modal.js
> +export default model("Attendees", attendeeSchema);
Change `"Attendees"` as `"attendees"`

2021-03-04 14:16 UTC, ebonynon commented on src/api/attendees/attendee.modal.js
> +    firstName: { type: String, required: true },
Make as unique and lowercase  `unique: true, lowercase: true`

2021-03-07 14:39 UTC, LayanJay reviewed
Resolved

2021-03-07 16:14 UTC, merged