Simple Health Check working
sliit-foss/rsvp pull request #35
Opened 2021-03-16 16:34 UTC by SahasR

If additional functionality required please label issue as WIP

2021-03-16 16:46 UTC, Shehanka requested changes

2021-03-16 16:46 UTC, Shehanka commented on package.json
> +    ""
@SahasR what is this ""

2021-03-16 17:49 UTC, SahasR commented on package.json
> +    ""
A Node Module used that can be called to a HealthCheck

2021-03-16 17:50 UTC, SahasR commented on package.json
> +    ""
Wait a minute what is it doing inside package.json -_-

2021-03-17 14:56 UTC, SahasR commented
Athi yanthan checks pass wuna

2021-03-23 01:21 UTC, Shehanka approved these changes

2021-03-23 01:21 UTC, merged