auth
sliit-foss/rsvp pull request #38
Opened 2021-05-12 01:25 UTC by Bawanthathilan

## Purpose

The purpose of this PR is to fix #24 

## Goals
Auth Endpoint Implementation

## Approach

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x ] I have performed a self-review of my own code
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Related PRs
 

## Learning

2021-05-12 10:38 UTC, Shehanka requested changes

2021-05-12 10:38 UTC, Shehanka commented on src/api/auth/auth.controller.js
> +    logger.info('auth.controller.js createAdmin(): ' + JSON.parse(req.body));
don't log all the things cuz body contains password also 😂

2021-05-13 04:30 UTC, Shehanka commented
@sithumonline you do the changes?

2021-05-13 04:34 UTC, sithumonline commented
> @sithumonline you do the changes?

yp

2021-05-14 11:56 UTC, sithumonline commented
switch to #41

2021-05-14 11:56 UTC, closed without merging