Auth by Bawwa
sliit-foss/rsvp pull request #41
Opened 2021-05-14 11:55 UTC by sithumonline

## Purpose

The purpose of this PR is to fix #<issue-number>

## Goals

## Approach

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have performed a self-review of my own code
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Related PRs
 

## Learning

2021-05-22 14:51 UTC, Shehanka requested changes

2021-05-22 14:51 UTC, Shehanka commented on src/api/auth/auth.controller.js
> +    //logger.info('auth.controller.js createAdmin(): ' + JSON.parse(req.body));
remove this unused comment

2021-05-22 14:51 UTC, Shehanka commented on src/app.js
>  //app.use(cors({ origin: true, credentials: true }));
why cors disabled?

2021-05-30 03:35 UTC, sithumonline commented
I fixed this issue with `local` but now we have to implement this for `JWT` as we couldn't do auth with `local` (smile in pain github edition)

2021-05-30 08:30 UTC, Shehanka approved these changes
Good job

2021-05-30 08:30 UTC, merged