Fixed bug in event validation
sliit-foss/rsvp pull request #88
Opened 2022-01-25 18:43 UTC by Akalanka47000

2022-01-27 15:51 UTC, Shehanka requested changes

2022-01-27 15:51 UTC, Shehanka commented on src/api/events/event.service.js
> +  if(duplicateEvents.length > 0 && duplicateEvents[0]._id != id){
use `duplicateEvents[0]?._id`

2022-01-31 18:56 UTC, Akalanka47000 commented on src/api/events/event.service.js
> +  if(duplicateEvents.length > 0 && duplicateEvents[0]._id != id){
I tried using the suggested syntax, but the condition logic fails once the duplicateEvents.length >0 condition is removed. The idea is that for the duplicate error message to show , there should be duplicate events in the array as well as the event should not be equal to the id of the event being updated. With just duplicateEvents[0]?._id != id it evaluates to undefined != id once there are no duplicates which always results in the error response being returned

2022-02-06 08:59 UTC, Shehanka approved these changes

2022-02-06 09:00 UTC, merged